@startuml

class BD {
    - addr : string
    - port : int 
    - cle : string
    - type_requete : list
    + acces_rapport()
    + enregistrer_rapport()
    + envoyer_requete(type_requete)
}

class Client {
    - id: int 
    - port : int 
    - addr : int 
    - num_simulation: int
    + envoyer_drone(id)
    + gerer_modeActionSM()
    + generer_rapport()
    + cloturer_mission()
}

class Simulation {
    - id : int
    - terrain: int
    - client : Client
    - unite : list<Unité>
    - unite_adverse : list<Unité>
}

class Unité {
    - drones: list<Drone>
    - sousmarins: list<SousMarin>
}

class SousMarin {
    - cap : tuple
    - position : tuple
    - mode : int 
    - dronesAlloués: int
    + attaquer()
    + changer_cap()
    + ecouter()
    + blanchir()
    + afficher_position()
}

class Drone {
    - id : int 
    - num_serie : int
    - position : tuple 
    - cap : tuple 
    + envoyer_position()
    + prise_image()
    + prise_son()
    + retour()
    + exploser()
    + reperage()
}


class ControleurClient {
    + recuperer_donnees()
    + mettre_a_jour_simulation()
}

BD <-- Client
ControleurClient "1" -- "1" Client : gère

Client *-- Simulation

Simulation *- Unité
Unité *-- Drone
Unité *-- SousMarin
SousMarin o-- Drone

@enduml
