# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Serveur - untitledbtCmgx.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

import sys
from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *
from PyQt5 import QtWidgets

class Ui_Serveur(object):
    def setupUi(self, Serveur):
        if not Serveur.objectName():
            Serveur.setObjectName(u"Serveur")
        Serveur.setWindowModality(Qt.NonModal)
        Serveur.resize(724, 811)
        Serveur.setDocumentMode(False)
        Serveur.setTabShape(QTabWidget.Triangular)
        self.centralwidget = QWidget(Serveur)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(20, 60, 681, 711))
        self.tab1 = QWidget()
        self.tab1.setObjectName(u"tab1")
        self.lineEdit = QLineEdit(self.tab1)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(290, 60, 113, 21))
        self.label = QLabel(self.tab1)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(110, 60, 181, 16))
        self.pushButton_4 = QPushButton(self.tab1)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(100, 140, 141, 41))
        self.radioButton = QRadioButton(self.tab1)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setGeometry(QRect(110, 80, 211, 20))
        self.radioButton_2 = QRadioButton(self.tab1)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setGeometry(QRect(110, 100, 201, 20))
        self.radioButton_3 = QRadioButton(self.tab1)
        self.radioButton_3.setObjectName(u"radioButton_3")
        self.radioButton_3.setGeometry(QRect(110, 120, 151, 20))
        self.plainTextEdit = QPlainTextEdit(self.tab1)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(110, 190, 481, 311))
        self.pushButton = QPushButton(self.tab1)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(240, 140, 131, 41))
        self.progressBar = QProgressBar(self.tab1)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(110, 510, 118, 23))
        self.progressBar.setValue(24)
        self.tabWidget.addTab(self.tab1, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.pushButton_2 = QPushButton(self.tab_2)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(200, 70, 113, 32))
        self.pushButton_5 = QPushButton(self.tab_2)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(200, 100, 113, 32))
        self.pushButton_6 = QPushButton(self.tab_2)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(260, 420, 111, 31))
        self.listView = QListView(self.tab_2)
        self.listView.setObjectName(u"listView")
        self.listView.setGeometry(QRect(320, 60, 241, 221))
        self.label_2 = QLabel(self.tab_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(320, 310, 141, 16))
        self.spinBox = QSpinBox(self.tab_2)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(410, 350, 42, 22))
        self.spinBox_2 = QSpinBox(self.tab_2)
        self.spinBox_2.setObjectName(u"spinBox_2")
        self.spinBox_2.setGeometry(QRect(410, 380, 42, 22))
        self.label_3 = QLabel(self.tab_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(190, 350, 201, 20))
        self.label_4 = QLabel(self.tab_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(190, 380, 221, 16))
        self.verticalSlider = QSlider(self.tab_2)
        self.verticalSlider.setObjectName(u"verticalSlider")
        self.verticalSlider.setGeometry(QRect(570, 70, 22, 221))
        self.verticalSlider.setOrientation(Qt.Vertical)
        self.lineEdit_2 = QLineEdit(self.tab_2)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(460, 310, 101, 21))
        self.progressBar_2 = QProgressBar(self.tab_2)
        self.progressBar_2.setObjectName(u"progressBar_2")
        self.progressBar_2.setGeometry(QRect(320, 290, 131, 16))
        self.progressBar_2.setValue(24)
        self.pushButton_3 = QPushButton(self.tab_2)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(370, 420, 113, 32))
        self.pushButton_10 = QPushButton(self.tab_2)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(260, 460, 221, 31))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.tabWidget_2 = QTabWidget(self.tab)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(40, 70, 591, 461))
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.label_15 = QLabel(self.tab_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(70, 60, 60, 16))
        self.label_16 = QLabel(self.tab_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(100, 90, 60, 16))
        self.label_17 = QLabel(self.tab_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(100, 120, 71, 16))
        self.label_18 = QLabel(self.tab_3)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(380, 90, 60, 16))
        self.label_19 = QLabel(self.tab_3)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(380, 120, 60, 16))
        self.label_20 = QLabel(self.tab_3)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(70, 170, 60, 16))
        self.label_21 = QLabel(self.tab_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(100, 200, 60, 16))
        self.label_22 = QLabel(self.tab_3)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(100, 220, 71, 16))
        self.label_23 = QLabel(self.tab_3)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(380, 200, 60, 16))
        self.label_24 = QLabel(self.tab_3)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(380, 230, 60, 16))
        self.label_25 = QLabel(self.tab_3)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(70, 270, 60, 16))
        self.label_26 = QLabel(self.tab_3)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(100, 300, 60, 16))
        self.label_27 = QLabel(self.tab_3)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(100, 320, 71, 16))
        self.label_28 = QLabel(self.tab_3)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(380, 300, 60, 16))
        self.label_29 = QLabel(self.tab_3)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(380, 320, 60, 16))
        self.doubleSpinBox_9 = QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_9.setObjectName(u"doubleSpinBox_9")
        self.doubleSpinBox_9.setGeometry(QRect(180, 90, 62, 22))
        self.doubleSpinBox_10 = QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_10.setObjectName(u"doubleSpinBox_10")
        self.doubleSpinBox_10.setGeometry(QRect(240, 90, 62, 22))
        self.doubleSpinBox_11 = QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_11.setObjectName(u"doubleSpinBox_11")
        self.doubleSpinBox_11.setGeometry(QRect(310, 90, 62, 22))
        self.doubleSpinBox_12 = QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_12.setObjectName(u"doubleSpinBox_12")
        self.doubleSpinBox_12.setGeometry(QRect(180, 120, 62, 22))
        self.doubleSpinBox_13 = QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_13.setObjectName(u"doubleSpinBox_13")
        self.doubleSpinBox_13.setGeometry(QRect(250, 120, 62, 22))
        self.doubleSpinBox_14 = QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_14.setObjectName(u"doubleSpinBox_14")
        self.doubleSpinBox_14.setGeometry(QRect(310, 120, 62, 22))
        self.doubleSpinBox_15 = QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_15.setObjectName(u"doubleSpinBox_15")
        self.doubleSpinBox_15.setGeometry(QRect(180, 200, 62, 22))
        self.doubleSpinBox_16 = QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_16.setObjectName(u"doubleSpinBox_16")
        self.doubleSpinBox_16.setGeometry(QRect(240, 200, 62, 22))
        self.doubleSpinBox_17 = QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_17.setObjectName(u"doubleSpinBox_17")
        self.doubleSpinBox_17.setGeometry(QRect(300, 200, 62, 22))
        self.doubleSpinBox_18 = QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_18.setObjectName(u"doubleSpinBox_18")
        self.doubleSpinBox_18.setGeometry(QRect(180, 220, 62, 22))
        self.doubleSpinBox_19 = QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_19.setObjectName(u"doubleSpinBox_19")
        self.doubleSpinBox_19.setGeometry(QRect(240, 220, 62, 22))
        self.doubleSpinBox_20 = QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_20.setObjectName(u"doubleSpinBox_20")
        self.doubleSpinBox_20.setGeometry(QRect(300, 220, 62, 22))
        self.doubleSpinBox_21 = QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_21.setObjectName(u"doubleSpinBox_21")
        self.doubleSpinBox_21.setGeometry(QRect(180, 300, 62, 22))
        self.doubleSpinBox_22 = QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_22.setObjectName(u"doubleSpinBox_22")
        self.doubleSpinBox_22.setGeometry(QRect(240, 300, 62, 22))
        self.doubleSpinBox_23 = QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_23.setObjectName(u"doubleSpinBox_23")
        self.doubleSpinBox_23.setGeometry(QRect(300, 300, 62, 22))
        self.doubleSpinBox_24 = QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_24.setObjectName(u"doubleSpinBox_24")
        self.doubleSpinBox_24.setGeometry(QRect(180, 320, 62, 22))
        self.doubleSpinBox_25 = QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_25.setObjectName(u"doubleSpinBox_25")
        self.doubleSpinBox_25.setGeometry(QRect(240, 320, 62, 22))
        self.doubleSpinBox_26 = QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_26.setObjectName(u"doubleSpinBox_26")
        self.doubleSpinBox_26.setGeometry(QRect(300, 320, 62, 22))
        self.label_30 = QLabel(self.tab_3)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(40, 30, 521, 16))
        self.pushButton_9 = QPushButton(self.tab_3)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(400, 370, 113, 32))
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.doubleSpinBox = QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox.setObjectName(u"doubleSpinBox")
        self.doubleSpinBox.setGeometry(QRect(150, 70, 62, 22))
        self.doubleSpinBox_2 = QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox_2.setObjectName(u"doubleSpinBox_2")
        self.doubleSpinBox_2.setGeometry(QRect(220, 70, 62, 22))
        self.doubleSpinBox_3 = QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox_3.setObjectName(u"doubleSpinBox_3")
        self.doubleSpinBox_3.setGeometry(QRect(290, 70, 62, 22))
        self.doubleSpinBox_4 = QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox_4.setObjectName(u"doubleSpinBox_4")
        self.doubleSpinBox_4.setGeometry(QRect(150, 100, 62, 22))
        self.doubleSpinBox_5 = QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox_5.setObjectName(u"doubleSpinBox_5")
        self.doubleSpinBox_5.setGeometry(QRect(220, 100, 62, 22))
        self.doubleSpinBox_6 = QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox_6.setObjectName(u"doubleSpinBox_6")
        self.doubleSpinBox_6.setGeometry(QRect(290, 100, 62, 22))
        self.label_8 = QLabel(self.tab_4)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(80, 100, 60, 16))
        self.label_9 = QLabel(self.tab_4)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(80, 70, 60, 16))
        self.label_10 = QLabel(self.tab_4)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(80, 190, 81, 16))
        self.label_11 = QLabel(self.tab_4)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(80, 130, 60, 16))
        self.doubleSpinBox_7 = QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox_7.setObjectName(u"doubleSpinBox_7")
        self.doubleSpinBox_7.setGeometry(QRect(150, 130, 62, 22))
        self.label_12 = QLabel(self.tab_4)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(80, 160, 111, 16))
        self.doubleSpinBox_8 = QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox_8.setObjectName(u"doubleSpinBox_8")
        self.doubleSpinBox_8.setGeometry(QRect(190, 160, 62, 22))
        self.spinBox_4 = QSpinBox(self.tab_4)
        self.spinBox_4.setObjectName(u"spinBox_4")
        self.spinBox_4.setGeometry(QRect(170, 190, 42, 22))
        self.spinBox_5 = QSpinBox(self.tab_4)
        self.spinBox_5.setObjectName(u"spinBox_5")
        self.spinBox_5.setGeometry(QRect(220, 190, 42, 22))
        self.spinBox_6 = QSpinBox(self.tab_4)
        self.spinBox_6.setObjectName(u"spinBox_6")
        self.spinBox_6.setGeometry(QRect(270, 190, 42, 22))
        self.pushButton_8 = QPushButton(self.tab_4)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(280, 230, 113, 32))
        self.label_13 = QLabel(self.tab_4)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(360, 70, 60, 16))
        self.label_14 = QLabel(self.tab_4)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(360, 100, 60, 16))
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.checkBox = QCheckBox(self.tab_5)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(220, 90, 87, 20))
        self.checkBox_2 = QCheckBox(self.tab_5)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(220, 110, 101, 20))
        self.checkBox_3 = QCheckBox(self.tab_5)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setGeometry(QRect(220, 130, 87, 20))
        self.checkBox_4 = QCheckBox(self.tab_5)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.checkBox_4.setGeometry(QRect(220, 150, 151, 20))
        self.label_31 = QLabel(self.tab_5)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(140, 50, 131, 20))
        self.comboBox_2 = QComboBox(self.tab_5)
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(270, 50, 91, 32))
        self.pushButton_11 = QPushButton(self.tab_5)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(230, 180, 113, 32))
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab4 = QWidget()
        self.tab4.setObjectName(u"tab4")
        self.spinBox_3 = QSpinBox(self.tab4)
        self.spinBox_3.setObjectName(u"spinBox_3")
        self.spinBox_3.setGeometry(QRect(300, 80, 42, 22))
        self.label_5 = QLabel(self.tab4)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(180, 80, 111, 20))
        self.label_7 = QLabel(self.tab4)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(180, 100, 121, 16))
        self.checkBox_5 = QCheckBox(self.tab4)
        self.checkBox_5.setObjectName(u"checkBox_5")
        self.checkBox_5.setGeometry(QRect(300, 100, 87, 20))
        self.checkBox_6 = QCheckBox(self.tab4)
        self.checkBox_6.setObjectName(u"checkBox_6")
        self.checkBox_6.setGeometry(QRect(390, 100, 87, 20))
        self.pushButton_7 = QPushButton(self.tab4)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(250, 140, 113, 32))
        self.label_6 = QLabel(self.tab4)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(160, 60, 111, 20))
        self.comboBox = QComboBox(self.tab4)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(300, 50, 121, 32))
        self.tabWidget_2.addTab(self.tab4, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.pushButton_12 = QPushButton(self.tab_6)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(190, 280, 151, 32))
        self.label_32 = QLabel(self.tab_6)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(190, 200, 111, 20))
        self.spinBox_7 = QSpinBox(self.tab_6)
        self.spinBox_7.setObjectName(u"spinBox_7")
        self.spinBox_7.setGeometry(QRect(320, 200, 42, 22))
        self.spinBox_8 = QSpinBox(self.tab_6)
        self.spinBox_8.setObjectName(u"spinBox_8")
        self.spinBox_8.setGeometry(QRect(220, 250, 42, 22))
        self.label_33 = QLabel(self.tab_6)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(270, 250, 60, 16))
        self.radioButton_6 = QRadioButton(self.tab_6)
        self.radioButton_6.setObjectName(u"radioButton_6")
        self.radioButton_6.setGeometry(QRect(190, 230, 171, 20))
        self.tabWidget_2.addTab(self.tab_6, "")
        self.pushButton_13 = QPushButton(self.tab)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(220, 610, 241, 41))
        self.radioButton_4 = QRadioButton(self.tab)
        self.radioButton_4.setObjectName(u"radioButton_4")
        self.radioButton_4.setGeometry(QRect(280, 550, 121, 20))
        self.radioButton_5 = QRadioButton(self.tab)
        self.radioButton_5.setObjectName(u"radioButton_5")
        self.radioButton_5.setGeometry(QRect(280, 580, 100, 20))
        self.tabWidget.addTab(self.tab, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.groupBox = QGroupBox(self.tab_7)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 50, 141, 461))
        self.groupBox_2 = QGroupBox(self.tab_7)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 520, 651, 131))
        self.groupBox_3 = QGroupBox(self.tab_7)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(170, 50, 471, 461))
        self.frame = QFrame(self.groupBox_3)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 20, 471, 431))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.tabWidget.addTab(self.tab_7, "")
        Serveur.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(Serveur)
        self.statusbar.setObjectName(u"statusbar")
        Serveur.setStatusBar(self.statusbar)

        self.retranslateUi(Serveur)

        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Serveur)
    # setupUi

    def retranslateUi(self, Serveur):
        Serveur.setWindowTitle(QCoreApplication.translate("Serveur", u"Serveur", None))
        self.label.setText(QCoreApplication.translate("Serveur", u"Saisir un num\u00e9ro de mission", None))
        self.pushButton_4.setText(QCoreApplication.translate("Serveur", u"Ouvrir le rapport", None))
        self.radioButton.setText(QCoreApplication.translate("Serveur", u"Rapport des d\u00e9placements", None))
        self.radioButton_2.setText(QCoreApplication.translate("Serveur", u"Rapport des d\u00e9tections", None))
        self.radioButton_3.setText(QCoreApplication.translate("Serveur", u"Rapport de mission", None))
        self.plainTextEdit.setPlainText(QCoreApplication.translate("Serveur", u"En attente", None))
        self.pushButton.setText(QCoreApplication.translate("Serveur", u"G\u00e9n\u00e9rer un pdf", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), QCoreApplication.translate("Serveur", u"Consulter un rapport", None))
        self.pushButton_2.setText(QCoreApplication.translate("Serveur", u"Saisir dr\u00f4ne", None))
        self.pushButton_5.setText(QCoreApplication.translate("Serveur", u"Saisir navire", None))
        self.pushButton_6.setText(QCoreApplication.translate("Serveur", u"Cr\u00e9er l'unit\u00e9", None))
        self.label_2.setText(QCoreApplication.translate("Serveur", u"Nombres disponibles:", None))
        self.label_3.setText(QCoreApplication.translate("Serveur", u"S\u00e9lectionner nb dr\u00f4nes souhait\u00e9s", None))
        self.label_4.setText(QCoreApplication.translate("Serveur", u"S\u00e9lectionner nb navires souhait\u00e9s", None))
        self.pushButton_3.setText(QCoreApplication.translate("Serveur", u"R\u00e9initialis\u00e9", None))
        self.pushButton_10.setText(QCoreApplication.translate("Serveur", u"Cr\u00e9er une simulation", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Serveur", u"Cr\u00e9er une unit\u00e9", None))
        self.label_15.setText(QCoreApplication.translate("Serveur", u"Point A:", None))
        self.label_16.setText(QCoreApplication.translate("Serveur", u"- Latitude", None))
        self.label_17.setText(QCoreApplication.translate("Serveur", u"- Longitude", None))
        self.label_18.setText(QCoreApplication.translate("Serveur", u"N", None))
        self.label_19.setText(QCoreApplication.translate("Serveur", u"W", None))
        self.label_20.setText(QCoreApplication.translate("Serveur", u"Point B:", None))
        self.label_21.setText(QCoreApplication.translate("Serveur", u"- Latitiude", None))
        self.label_22.setText(QCoreApplication.translate("Serveur", u"- Longitude", None))
        self.label_23.setText(QCoreApplication.translate("Serveur", u"N", None))
        self.label_24.setText(QCoreApplication.translate("Serveur", u"W", None))
        self.label_25.setText(QCoreApplication.translate("Serveur", u"Point C:", None))
        self.label_26.setText(QCoreApplication.translate("Serveur", u"-Latitude", None))
        self.label_27.setText(QCoreApplication.translate("Serveur", u"-Longitude", None))
        self.label_28.setText(QCoreApplication.translate("Serveur", u"N", None))
        self.label_29.setText(QCoreApplication.translate("Serveur", u"W", None))
        self.label_30.setText(QCoreApplication.translate("Serveur", u"Veuillez d\u00e9finir un terrain triangulaire dans le syst\u00e8me de coordonn\u00e9es de navigation", None))
        self.pushButton_9.setText(QCoreApplication.translate("Serveur", u"Relier", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QCoreApplication.translate("Serveur", u"D\u00e9finir terrain", None))
        self.label_8.setText(QCoreApplication.translate("Serveur", u"Longitude", None))
        self.label_9.setText(QCoreApplication.translate("Serveur", u"Latitude", None))
        self.label_10.setText(QCoreApplication.translate("Serveur", u"Heure (UTC)", None))
        self.label_11.setText(QCoreApplication.translate("Serveur", u"Direction", None))
        self.label_12.setText(QCoreApplication.translate("Serveur", u"Vitesse (noeuds)", None))
        self.pushButton_8.setText(QCoreApplication.translate("Serveur", u"Placer", None))
        self.label_13.setText(QCoreApplication.translate("Serveur", u"N", None))
        self.label_14.setText(QCoreApplication.translate("Serveur", u"W", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QCoreApplication.translate("Serveur", u"Placer unit\u00e9s", None))
        self.checkBox.setText(QCoreApplication.translate("Serveur", u"Rep\u00e9rage", None))
        self.checkBox_2.setText(QCoreApplication.translate("Serveur", u"Surveillance", None))
        self.checkBox_3.setText(QCoreApplication.translate("Serveur", u"Attaque", None))
        self.checkBox_4.setText(QCoreApplication.translate("Serveur", u"Branchir une zone", None))
        self.label_31.setText(QCoreApplication.translate("Serveur", u"Choisir votre unit\u00e9:", None))
        self.pushButton_11.setText(QCoreApplication.translate("Serveur", u"Confirmer", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QCoreApplication.translate("Serveur", u"D\u00e9finir mode op\u00e9ration", None))
        self.label_5.setText(QCoreApplication.translate("Serveur", u"Nb dr\u00f4nes actifs", None))
        self.label_7.setText(QCoreApplication.translate("Serveur", u"Mode op\u00e9ration :", None))
        self.checkBox_5.setText(QCoreApplication.translate("Serveur", u"Offensive", None))
        self.checkBox_6.setText(QCoreApplication.translate("Serveur", u"Passive", None))
        self.pushButton_7.setText(QCoreApplication.translate("Serveur", u"Appliquer", None))
        self.label_6.setText(QCoreApplication.translate("Serveur", u"Saisir <id> unit\u00e9s", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab4), QCoreApplication.translate("Serveur", u"D\u00e9finir OPFOR", None))
        self.pushButton_12.setText(QCoreApplication.translate("Serveur", u"Attribuer le client", None))
        self.label_32.setText(QCoreApplication.translate("Serveur", u"Choisir <id> Client", None))
        self.label_33.setText(QCoreApplication.translate("Serveur", u"minutes", None))
        self.radioButton_6.setText(QCoreApplication.translate("Serveur", u"Imposer une dur\u00e9e", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), QCoreApplication.translate("Serveur", u"Attribuer Client", None))
        self.pushButton_13.setText(QCoreApplication.translate("Serveur", u"Lancer la simulation", None))
        self.radioButton_4.setText(QCoreApplication.translate("Serveur", u"Mode en direct", None))
        self.radioButton_5.setText(QCoreApplication.translate("Serveur", u"Mode replay", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Serveur", u"G\u00e9rer une simulation", None))
        self.groupBox.setTitle(QCoreApplication.translate("Serveur", u"Messages", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Serveur", u"Informations", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("Serveur", u"SITAC", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QCoreApplication.translate("Serveur", u"Visualisation", None))
    # retranslateUi
class MainWindow(QMainWindow, Ui_Serveur):
    def __init__(self):
        super(MainWindow, self).__init__()
        self.setupUi(self)

if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())
