@startuml

    actor Utilisateur
    participant GUI
    participant Controler
    participant Data_Access_Object
    participant Data
    participant DB_Manager
    participant Net
    participant Messages

loop interaction
    Utilisateur -> GUI: Utilisation de l'interface
    GUI -> Controler: Demande de traitement
    Controler -> Data: Demande de modification
    Data -> Data_Access_Object:  Modification des données
    Data_Access_Object --> Data: Données modifiées
    Data --> GUI: Afficher modification
end
    Utilisateur -> GUI: Générer un rapport
    GUI-> Controler : Demande génération de rapport
    Controler -> Data: Chargement des données pour le rapport
    Data -> Data_Access_Object: Accès aux données
    Data_Access_Object -> DB_Manager: Requête à la base de données
    DB_Manager --> Data_Access_Object: Résultat de la requête
    Data_Access_Object --> Data: Rapport généré
    Data --> Controler: Données chargées
    Controler --> GUI : Rapport disponible
    Controler -> Net: Envoi de données
    Net --> Messages: Transmission fin simulation
@enduml
