@startuml

participant Client
participant Serveur

Client -> Serveur: Requête de connexion
Serveur -> Client: Attribution d'un identifiant unique

note right of Serveur
    Le serveur attribue un identifiant
    unique à chaque client.
end note

Client -> Serveur: Requête de démarrage de simulation
Serveur -> Client: Confirmation de démarrage de simulation

note right of Serveur
    Le serveur gère le démarrage de
    la simulation pour chaque client
    en utilisant l'identifiant attribué.
end note
@enduml
