@startuml
package "Modèle entité-association (MEA)" {
    entity Drone {
        + id INT (PK)
        drone_name VARCHAR
        drone_type VARCHAR
        drone_status VARCHAR
        drone_position_x FLOAT
        drone_position_y FLOAT
        drone_position_z FLOAT
    }

    entity Navire {
        + id INT (PK)
        navire_name VARCHAR
        navire_type VARCHAR
        navire_status VARCHAR
        navire_position_x FLOAT
        navire_position_y FLOAT
        navire_position_z FLOAT
    }

    entity Rapport {
        + id INT (PK)
        rapport_name VARCHAR
        rapport_description TEXT
        rapport_date DATETIME
    }

    entity Rapport_Drone {
        
    }
    note right of Rapport_Drone
    Remplace un losange pour représenter la relation entre Rapport et Drone
    end note

    Drone "0" -- "n" Rapport_Drone : génère
    Rapport "0" -- "n" Rapport_Drone : participe à
    Navire "1" -- "n" Rapport : concerne

}
@enduml